<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class ProductCatalogSeeder extends Seeder
{
    public function run()
    {
        $now = Carbon::now();

        // ======================================================
        // 1. СОБАКИ -> КОРМА -> СУХИЕ КОРМА (category_id=3)
        // ======================================================
        DB::table('products')->insert([
            [
                'id' => 21,
                'name' => 'Grandin Hypoallergenic ягненок',
                'slug' => 'grandin-hypoallergenic-yagnenok',
                'description' => 'Гипоаллергенный сухой корм для собак всех пород с ягненком. Беззерновой суперпремиум класс без курицы и говядины.',
                'brand_id' => 5,
                'category_id' => 3,
                'is_active' => 1,
                'meta_title' => 'Grandin Hypoallergenic сухой корм ягненок',
                'meta_description' => 'Гипоаллергенный корм Grandin с ягненком для собак всех пород без злаков суперпремиум класс',
                'meta_keywords' => 'grandin hypoallergenic,сухой корм собак,ягненок,гипоаллергенный корм собак',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 22,
                'name' => 'Klicker Adult лосось',
                'slug' => 'klicker-adult-los-os',
                'description' => 'Сухой корм для собак мелких пород с лососем. Высокая усвояемость и поддержка пищеварения.',
                'brand_id' => null,
                'category_id' => 3,
                'is_active' => 1,
                'meta_title' => 'Klicker Adult сухой корм лосось мелкие породы',
                'meta_description' => 'Премиум корм Klicker для мелких пород с лососем поддержка пищеварения',
                'meta_keywords' => 'klicker корм,сухой корм мелких собак,лосось собак',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 23,
                'name' => 'Royal Canin Mini Adult',
                'slug' => 'royal-canin-mini-adult',
                'description' => 'Сухой корм для взрослых собак мелких пород. Поддержка кожи и шерсти, высокая калорийность.',
                'brand_id' => 1,
                'category_id' => 3,
                'is_active' => 1,
                'meta_title' => 'Royal Canin Mini Adult сухой корм мелкие породы',
                'meta_description' => 'Корм Royal Canin для мелких взрослых собак поддержка кожи шерсти',
                'meta_keywords' => 'royal canin mini adult,сухой корм собак мелких пород',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 24,
                'name' => 'ABBA Premium ягненок',
                'slug' => 'abba-premium-yagnenok',
                'description' => 'Сухой корм суперпремиум с ягненком для всех пород. Естественные ингредиенты без ГМО.',
                'brand_id' => 2,
                'category_id' => 3,
                'is_active' => 1,
                'meta_title' => 'ABBA Premium сухой корм ягненок',
                'meta_description' => 'ABBA суперпремиум корм с ягненком для собак всех пород натуральные ингредиенты',
                'meta_keywords' => 'abba premium,ягненок сухой корм,суперпремиум собак',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 25,
                'name' => 'RURRI Classic говядина',
                'slug' => 'rurri-classic-govyadina',
                'description' => 'Сухой корм с говядиной для собак всех пород. Балансированное питание эконом класс.',
                'brand_id' => 3,
                'category_id' => 3,
                'is_active' => 1,
                'meta_title' => 'RURRI Classic говядина сухой корм',
                'meta_description' => 'Качественный корм RURRI Classic с говядиной для собак всех пород',
                'meta_keywords' => 'rurri classic,говядина корм собак,сухой корм эконом',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 26,
                'name' => 'Ownat Grain Free курица',
                'slug' => 'ownat-grain-free-kurica',
                'description' => 'Беззерновой сухой корм с курицей и рисом для собак всех пород. Холистик класс.',
                'brand_id' => 4,
                'category_id' => 3,
                'is_active' => 1,
                'meta_title' => 'Ownat Grain Free сухой корм курица',
                'meta_description' => 'Беззерновой корм Ownat Grain Free с курицей холистик класс для собак',
                'meta_keywords' => 'ownat grain free,курица беззерновой,холистик корм',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        DB::table('product_variations')->insert([
            [
                'id' => 41,
                'product_id' => 21,
                'name' => 'Grandin Hypoallergenic ягненок, 2.7 кг',
                'sku' => 'GRANDIN-1049894',
                'price' => 2499.00,
                'old_price' => null,
                'stock' => 50,
                'is_default' => 1,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 42,
                'product_id' => 21,
                'name' => 'Grandin Hypoallergenic ягненок, 11.2 кг',
                'sku' => 'GRANDIN-1049893',
                'price' => 7899.00,
                'old_price' => null,
                'stock' => 25,
                'is_default' => 0,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 43,
                'product_id' => 22,
                'name' => 'Klicker Adult лосось, 0.5 кг',
                'sku' => 'KLICKER-1060933',
                'price' => 1299.00,
                'old_price' => null,
                'stock' => 100,
                'is_default' => 1,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 44,
                'product_id' => 22,
                'name' => 'Klicker Adult лосось, 2 кг',
                'sku' => 'KLICKER-LOSOS-2KG',
                'price' => 3999.00,
                'old_price' => null,
                'stock' => 60,
                'is_default' => 0,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 45,
                'product_id' => 23,
                'name' => 'Royal Canin Mini Adult, 2 кг',
                'sku' => 'RC-MINI-ADULT-2KG',
                'price' => 3599.00,
                'old_price' => null,
                'stock' => 75,
                'is_default' => 1,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 46,
                'product_id' => 23,
                'name' => 'Royal Canin Mini Adult, 4 кг',
                'sku' => 'RC-MINI-ADULT-4KG',
                'price' => 5999.00,
                'old_price' => null,
                'stock' => 40,
                'is_default' => 0,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 47,
                'product_id' => 24,
                'name' => 'ABBA Premium ягненок, 3 кг',
                'sku' => 'ABBA-YAG-3KG',
                'price' => 2199.00,
                'old_price' => null,
                'stock' => 60,
                'is_default' => 1,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 48,
                'product_id' => 24,
                'name' => 'ABBA Premium ягненок, 12 кг',
                'sku' => 'ABBA-YAG-12KG',
                'price' => 6999.00,
                'old_price' => null,
                'stock' => 30,
                'is_default' => 0,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 49,
                'product_id' => 25,
                'name' => 'RURRI Classic говядина, 3 кг',
                'sku' => 'RURRI-GOV-3KG',
                'price' => 1599.00,
                'old_price' => 1799.00,
                'stock' => 80,
                'is_default' => 1,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 50,
                'product_id' => 25,
                'name' => 'RURRI Classic говядина, 15 кг',
                'sku' => 'RURRI-GOV-15KG',
                'price' => 5999.00,
                'old_price' => null,
                'stock' => 20,
                'is_default' => 0,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 51,
                'product_id' => 26,
                'name' => 'Ownat Grain Free курица, 2 кг',
                'sku' => 'OWNAT-KUR-2KG',
                'price' => 2299.00,
                'old_price' => null,
                'stock' => 45,
                'is_default' => 1,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 52,
                'product_id' => 26,
                'name' => 'Ownat Grain Free курица, 12 кг',
                'sku' => 'OWNAT-KUR-12KG',
                'price' => 7999.00,
                'old_price' => null,
                'stock' => 15,
                'is_default' => 0,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        // ======================================================
        // 2. КОШКИ -> КОРМА -> СУХИЕ КОРМА (category_id=21)
        // ======================================================
        DB::table('products')->insert([
            [
                'id' => 27,
                'name' => 'Klicker Sensitive Digestion',
                'slug' => 'klicker-sensitive-digestion',
                'description' => 'Сухой корм для кошек с чувствительным пищеварением. Легкоусвояемые ингредиенты.',
                'brand_id' => null,
                'category_id' => 21,
                'is_active' => 1,
                'meta_title' => 'Klicker Sensitive сухой корм кошки пищеварение',
                'meta_description' => 'Корм для кошек с чувствительным пищеварением Klicker легкоусвояемые ингредиенты',
                'meta_keywords' => 'klicker sensitive,сухой корм кошек,пищеварение кошки',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 28,
                'name' => 'Bozita Funktion Indoor',
                'slug' => 'bozita-funktion-indoor',
                'description' => 'Сухой корм для кошек живущих в доме. Контроль веса и шерсти.',
                'brand_id' => null,
                'category_id' => 21,
                'is_active' => 1,
                'meta_title' => 'Bozita Funktion Indoor сухой корм кошки',
                'meta_description' => 'Корм для домашних кошек Bozita Funktion контроль веса шерсти',
                'meta_keywords' => 'bozita indoor,корм кошек дом,функциональный корм',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 29,
                'name' => 'Royal Canin Sterilised',
                'slug' => 'royal-canin-sterilised',
                'description' => 'Сухой корм для стерилизованных кошек. Поддержка мочевыводящей системы.',
                'brand_id' => 1,
                'category_id' => 21,
                'is_active' => 1,
                'meta_title' => 'Royal Canin Sterilised сухой корм кошки',
                'meta_description' => 'Корм Royal Canin для стерилизованных кошек поддержка мочевыводящей системы',
                'meta_keywords' => 'royal canin sterilised,корм стерилизованных кошек',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 30,
                'name' => 'Grandin Hypo Cat',
                'slug' => 'grandin-hypo-cat',
                'description' => 'Гипоаллергенный сухой корм для кошек всех пород.',
                'brand_id' => 5,
                'category_id' => 21,
                'is_active' => 1,
                'meta_title' => 'Grandin Hypoallergenic сухой корм кошки',
                'meta_description' => 'Гипоаллергенный корм Grandin для кошек всех пород',
                'meta_keywords' => 'grandin hypo кошка,гипоаллергенный корм кошек',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 31,
                'name' => 'Ownat Classic курица',
                'slug' => 'ownat-classic-kurica-koshka',
                'description' => 'Сухой корм для кошек с курицей. Полнорационное питание.',
                'brand_id' => 4,
                'category_id' => 21,
                'is_active' => 1,
                'meta_title' => 'Ownat Classic сухой корм кошки курица',
                'meta_description' => 'Полнорационный корм Ownat Classic с курицей для кошек',
                'meta_keywords' => 'ownat classic кошка,курица корм кошек',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 32,
                'name' => 'RURRI Indoor',
                'slug' => 'rurri-indoor-koshka',
                'description' => 'Сухой корм для взрослых кошек живущих в помещении.',
                'brand_id' => 3,
                'category_id' => 21,
                'is_active' => 1,
                'meta_title' => 'RURRI Indoor сухой корм кошки',
                'meta_description' => 'Корм RURRI для взрослых кошек живущих в помещении',
                'meta_keywords' => 'rurri indoor,корм кошек помещение',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        DB::table('product_variations')->insert([
            [
                'id' => 53,
                'product_id' => 27,
                'name' => 'Klicker Sensitive Digestion, 1 кг',
                'sku' => 'KLICKER-SENS-1KG',
                'price' => 1399.00,
                'old_price' => null,
                'stock' => 80,
                'is_default' => 1,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 54,
                'product_id' => 27,
                'name' => 'Klicker Sensitive Digestion, 4 кг',
                'sku' => 'KLICKER-SENS-4KG',
                'price' => 4499.00,
                'old_price' => null,
                'stock' => 35,
                'is_default' => 0,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 55,
                'product_id' => 28,
                'name' => 'Bozita Funktion Indoor, 1.5 кг',
                'sku' => 'BOZITA-INDOOR-1.5',
                'price' => 1899.00,
                'old_price' => null,
                'stock' => 70,
                'is_default' => 1,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 56,
                'product_id' => 28,
                'name' => 'Bozita Funktion Indoor, 4 кг',
                'sku' => 'BOZITA-INDOOR-4KG',
                'price' => 4899.00,
                'old_price' => null,
                'stock' => 25,
                'is_default' => 0,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 57,
                'product_id' => 29,
                'name' => 'Royal Canin Sterilised, 2 кг',
                'sku' => 'RC-STER-2KG',
                'price' => 3499.00,
                'old_price' => null,
                'stock' => 60,
                'is_default' => 1,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 58,
                'product_id' => 29,
                'name' => 'Royal Canin Sterilised, 4 кг',
                'sku' => 'RC-STER-4KG',
                'price' => 5899.00,
                'old_price' => null,
                'stock' => 30,
                'is_default' => 0,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 59,
                'product_id' => 30,
                'name' => 'Grandin Hypo Cat, 2 кг',
                'sku' => 'GRANDIN-HYPOCAT-2',
                'price' => 2399.00,
                'old_price' => null,
                'stock' => 55,
                'is_default' => 1,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 60,
                'product_id' => 30,
                'name' => 'Grandin Hypo Cat, 10 кг',
                'sku' => 'GRANDIN-HYPOCAT-10',
                'price' => 7499.00,
                'old_price' => null,
                'stock' => 20,
                'is_default' => 0,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 61,
                'product_id' => 31,
                'name' => 'Ownat Classic курица, 1.5 кг',
                'sku' => 'OWNAT-KUR-KOSH-1.5',
                'price' => 1699.00,
                'old_price' => null,
                'stock' => 65,
                'is_default' => 1,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 62,
                'product_id' => 31,
                'name' => 'Ownat Classic курица, 7 кг',
                'sku' => 'OWNAT-KUR-KOSH-7',
                'price' => 4999.00,
                'old_price' => null,
                'stock' => 25,
                'is_default' => 0,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 63,
                'product_id' => 32,
                'name' => 'RURRI Indoor, 2 кг',
                'sku' => 'RURRI-INDOOR-2',
                'price' => 1799.00,
                'old_price' => null,
                'stock' => 75,
                'is_default' => 1,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 64,
                'product_id' => 32,
                'name' => 'RURRI Indoor, 10 кг',
                'sku' => 'RURRI-INDOOR-10',
                'price' => 5999.00,
                'old_price' => null,
                'stock' => 15,
                'is_default' => 0,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        // ======================================================
        // 3. СОБАКИ -> АМУНИЦИЯ -> ОШЕЙНИКИ И ПОВОДКИ (category_id=7)
        // ======================================================
        DB::table('products')->insert([
            [
                'id' => 33,
                'name' => 'Rungo K-9 ошейник',
                'slug' => 'rungo-k9-osheynik',
                'description' => 'Нейлоновый ошейник с ручкой для контроля собаки. Прочный и удобный.',
                'brand_id' => 10,
                'category_id' => 7,
                'is_active' => 1,
                'meta_title' => 'Rungo K-9 ошейник нейлоновый с ручкой',
                'meta_description' => 'Прочный ошейник Rungo K-9 с ручкой для собак всех размеров',
                'meta_keywords' => 'rungo k9,ошейник собак с ручкой,нейлоновый ошейник',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 34,
                'name' => 'Trixie кожаный ошейник',
                'slug' => 'trixie-kozhanii-osheynik',
                'description' => 'Натуральная кожа с металлическими заклепками. Классический дизайн.',
                'brand_id' => null,
                'category_id' => 7,
                'is_active' => 1,
                'meta_title' => 'Trixie кожаный ошейник собака',
                'meta_description' => 'Кожаный ошейник Trixie натуральная кожа для собак',
                'meta_keywords' => 'trixie кожаный,ошейник собака кожа',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 35,
                'name' => 'Ferplast парашютный ошейник',
                'slug' => 'ferplast-parashyutnyi-osheynik',
                'description' => 'Парашютная ткань легкая и прочная. Регулируемый размер.',
                'brand_id' => null,
                'category_id' => 7,
                'is_active' => 1,
                'meta_title' => 'Ferplast парашютный ошейник собака',
                'meta_description' => 'Легкий парашютный ошейник Ferplast для собак',
                'meta_keywords' => 'ferplast парашютный,ошейник легкий собака',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 36,
                'name' => 'Rogz ошейник Utility',
                'slug' => 'rogz-utility-osheynik',
                'description' => 'Усиленный нейлон с мягкой подкладкой. 5 точек фиксации.',
                'brand_id' => null,
                'category_id' => 7,
                'is_active' => 1,
                'meta_title' => 'Rogz Utility ошейник собака',
                'meta_description' => 'Прочный ошейник Rogz Utility усиленный нейлон',
                'meta_keywords' => 'rogz utility,ошейник собака усиленный',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 37,
                'name' => 'Hunter кожаный плетеный',
                'slug' => 'hunter-kozhanii-pletenyi',
                'description' => 'Ручная плетка из натуральной кожи. Эксклюзивный дизайн.',
                'brand_id' => null,
                'category_id' => 7,
                'is_active' => 1,
                'meta_title' => 'Hunter плетеный кожаный ошейник',
                'meta_description' => 'Эксклюзивный плетеный кожаный ошейник Hunter',
                'meta_keywords' => 'hunter плетеный,кожаный ошейник эксклюзив',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 38,
                'name' => 'Petzl ошейник альпинистский',
                'slug' => 'petzl-alpinistskii-osheynik',
                'description' => 'Сверхпрочный для рабочих собак. Используется кинологами.',
                'brand_id' => null,
                'category_id' => 7,
                'is_active' => 1,
                'meta_title' => 'Petzl альпинистский ошейник собака',
                'meta_description' => 'Сверхпрочный ошейник Petzl для рабочих собак',
                'meta_keywords' => 'petzl альпинистский,ошейник рабочие собаки',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        DB::table('product_variations')->insert([
            [
                'id' => 65,
                'product_id' => 33,
                'name' => 'Rungo K-9 ошейник, L (42-65 см)',
                'sku' => 'RUNGO-K9-L-1064128',
                'price' => 1749.00,
                'old_price' => null,
                'stock' => 25,
                'is_default' => 1,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 66,
                'product_id' => 33,
                'name' => 'Rungo K-9 ошейник, M (38-48 см)',
                'sku' => 'RUNGO-K9-M-1064127',
                'price' => 1499.00,
                'old_price' => 1599.00,
                'stock' => 10,
                'is_default' => 0,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 67,
                'product_id' => 34,
                'name' => 'Trixie кожаный ошейник, M (30-45 см)',
                'sku' => 'TRIXIE-LEATHER-M',
                'price' => 2199.00,
                'old_price' => null,
                'stock' => 40,
                'is_default' => 1,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 68,
                'product_id' => 34,
                'name' => 'Trixie кожаный ошейник, L (40-60 см)',
                'sku' => 'TRIXIE-LEATHER-L',
                'price' => 2799.00,
                'old_price' => null,
                'stock' => 20,
                'is_default' => 0,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 69,
                'product_id' => 35,
                'name' => 'Ferplast парашютный ошейник, S (25-40 см)',
                'sku' => 'FERPLAST-S',
                'price' => 1299.00,
                'old_price' => null,
                'stock' => 60,
                'is_default' => 1,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 70,
                'product_id' => 35,
                'name' => 'Ferplast парашютный ошейник, M (35-55 см)',
                'sku' => 'FERPLAST-M',
                'price' => 1599.00,
                'old_price' => null,
                'stock' => 35,
                'is_default' => 0,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 71,
                'product_id' => 36,
                'name' => 'Rogz Utility ошейник, M',
                'sku' => 'ROGZ-UTILITY-M',
                'price' => 2999.00,
                'old_price' => null,
                'stock' => 30,
                'is_default' => 1,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 72,
                'product_id' => 36,
                'name' => 'Rogz Utility ошейник, L',
                'sku' => 'ROGZ-UTILITY-L',
                'price' => 3499.00,
                'old_price' => null,
                'stock' => 15,
                'is_default' => 0,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 73,
                'product_id' => 37,
                'name' => 'Hunter кожаный плетеный, M',
                'sku' => 'HUNTER-PLET-M',
                'price' => 4999.00,
                'old_price' => null,
                'stock' => 10,
                'is_default' => 1,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 74,
                'product_id' => 37,
                'name' => 'Hunter кожаный плетеный, L',
                'sku' => 'HUNTER-PLET-L',
                'price' => 5999.00,
                'old_price' => null,
                'stock' => 5,
                'is_default' => 0,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 75,
                'product_id' => 38,
                'name' => 'Petzl ошейник альпинистский, L/XL',
                'sku' => 'PETZL-ALP-LXL',
                'price' => 7999.00,
                'old_price' => null,
                'stock' => 8,
                'is_default' => 1,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        // ======================================================
        // 4. КОШКИ -> НАПОЛНИТЕЛИ -> ДРЕВЕСНЫЕ (category_id=25)
        // ======================================================
        DB::table('products')->insert([
            [
                'id' => 39,
                'name' => 'Ever Clean Extra Strength',
                'slug' => 'ever-clean-extra-strength',
                'description' => 'Древесный наполнитель для кошек. Сильная комкуемость отличная нейтрализация запаха.',
                'brand_id' => null,
                'category_id' => 25,
                'is_active' => 1,
                'meta_title' => 'Ever Clean Extra Strength древесный наполнитель',
                'meta_description' => 'Премиум древесный наполнитель Ever Clean сильная комкуемость',
                'meta_keywords' => 'ever clean,древесный наполнитель кошки,премиум наполнитель',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 40,
                'name' => "Cat's Best Original",
                'slug' => 'cats-best-original',
                'description' => 'Натуральный гранулированный наполнитель из волокон целлюлозы. 100% биоразлагаемый.',
                'brand_id' => null,
                'category_id' => 25,
                'is_active' => 1,
                'meta_title' => "Cat's Best Original древесный наполнитель",
                'meta_description' => 'Натуральный древесный наполнитель Cat\'s Best из целлюлозы',
                'meta_keywords' => 'cats best,древесный натуральный,наполнитель кошки',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 41,
                'name' => 'Barsik Premium древесный',
                'slug' => 'barsik-premium-drevesnyi',
                'description' => 'Древесный наполнитель из опилок хвойных пород. Высокая впитываемость.',
                'brand_id' => null,
                'category_id' => 25,
                'is_active' => 1,
                'meta_title' => 'Barsik Premium древесный наполнитель кошки',
                'meta_description' => 'Древесный наполнитель Barsik Premium из хвойных пород',
                'meta_keywords' => 'barsik древесный,наполнитель кошки хвойный',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 42,
                'name' => 'Perfect Fit древесный',
                'slug' => 'perfect-fit-drevesnyi',
                'description' => 'Комкующийся древесный наполнитель. Натуральный состав без химии.',
                'brand_id' => null,
                'category_id' => 25,
                'is_active' => 1,
                'meta_title' => 'Perfect Fit древесный наполнитель',
                'meta_description' => 'Комкующийся древесный наполнитель Perfect Fit натуральный',
                'meta_keywords' => 'perfect fit древесный,комкующийся наполнитель',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 43,
                'name' => 'Сибирский лес премиум',
                'slug' => 'sibirskii-les-premium',
                'description' => 'Премиум древесный наполнитель. Сильный контроль запаха.',
                'brand_id' => null,
                'category_id' => 25,
                'is_active' => 1,
                'meta_title' => 'Сибирский лес премиум древесный наполнитель',
                'meta_description' => 'Премиум древесный наполнитель Сибирский лес контроль запаха',
                'meta_keywords' => 'сибирский лес,древесный премиум наполнитель',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 44,
                'name' => 'Травка-Сено древесный',
                'slug' => 'travka-seno-drevesnyi',
                'description' => 'Натуральный древесный наполнитель с экстрактами трав.',
                'brand_id' => null,
                'category_id' => 25,
                'is_active' => 1,
                'meta_title' => 'Травка-Сено древесный наполнитель кошки',
                'meta_description' => 'Древесный наполнитель Травка-Сено с экстрактами трав',
                'meta_keywords' => 'травка сено,древесный с травами наполнитель',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        DB::table('product_variations')->insert([
            [
                'id' => 76,
                'product_id' => 39,
                'name' => 'Ever Clean Extra Strength, 10 л',
                'sku' => 'EVERCLEAN-10L',
                'price' => 1499.00,
                'old_price' => null,
                'stock' => 40,
                'is_default' => 1,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 77,
                'product_id' => 39,
                'name' => 'Ever Clean Extra Strength, 20 л',
                'sku' => 'EVERCLEAN-20L',
                'price' => 2599.00,
                'old_price' => null,
                'stock' => 25,
                'is_default' => 0,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 78,
                'product_id' => 40,
                'name' => "Cat's Best Original, 6 кг",
                'sku' => 'CATS-BEST-6KG',
                'price' => 1299.00,
                'old_price' => null,
                'stock' => 60,
                'is_default' => 1,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 79,
                'product_id' => 40,
                'name' => "Cat's Best Original, 17 кг",
                'sku' => 'CATS-BEST-17KG',
                'price' => 2999.00,
                'old_price' => null,
                'stock' => 30,
                'is_default' => 0,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 80,
                'product_id' => 41,
                'name' => 'Barsik Premium древесный, 5 л',
                'sku' => 'BARSIK-5L',
                'price' => 899.00,
                'old_price' => null,
                'stock' => 80,
                'is_default' => 1,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 81,
                'product_id' => 41,
                'name' => 'Barsik Premium древесный, 10 л',
                'sku' => 'BARSIK-10L',
                'price' => 1499.00,
                'old_price' => null,
                'stock' => 50,
                'is_default' => 0,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 82,
                'product_id' => 42,
                'name' => 'Perfect Fit древесный, 8 л',
                'sku' => 'PERFECTFIT-8L',
                'price' => 1099.00,
                'old_price' => null,
                'stock' => 70,
                'is_default' => 1,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 83,
                'product_id' => 42,
                'name' => 'Perfect Fit древесный, 15 л',
                'sku' => 'PERFECTFIT-15L',
                'price' => 1999.00,
                'old_price' => null,
                'stock' => 40,
                'is_default' => 0,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 84,
                'product_id' => 43,
                'name' => 'Сибирский лес премиум, 10 л',
                'sku' => 'SIBLES-10L',
                'price' => 1399.00,
                'old_price' => null,
                'stock' => 45,
                'is_default' => 1,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 85,
                'product_id' => 43,
                'name' => 'Сибирский лес премиум, 20 л',
                'sku' => 'SIBLES-20L',
                'price' => 2499.00,
                'old_price' => null,
                'stock' => 20,
                'is_default' => 0,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 86,
                'product_id' => 44,
                'name' => 'Травка-Сено древесный, 7 л',
                'sku' => 'TRAVKA-7L',
                'price' => 1199.00,
                'old_price' => null,
                'stock' => 55,
                'is_default' => 1,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 87,
                'product_id' => 44,
                'name' => 'Травка-Сено древесный, 14 л',
                'sku' => 'TRAVKA-14L',
                'price' => 2099.00,
                'old_price' => null,
                'stock' => 30,
                'is_default' => 0,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        // ======================================================
        // 5. СОБАКИ -> ИГРУШКИ -> МЯЧИКИ И ФРИСБИ (category_id=11)
        // ======================================================
        DB::table('products')->insert([
            [
                'id' => 45,
                'name' => 'Kong Classic красный',
                'slug' => 'kong-classic-krasnyi',
                'description' => 'Классическая резиновая игрушка для жевания и апортировки. Неотъемлемый элемент дрессировки.',
                'brand_id' => null,
                'category_id' => 11,
                'is_active' => 1,
                'meta_title' => 'Kong Classic красный мячик собака',
                'meta_description' => 'Резиновая игрушка Kong Classic для собак жевание апортировка',
                'meta_keywords' => 'kong classic,мячик собака резиновый,игрушка для жевания',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 46,
                'name' => 'Trixie теннисный мячик',
                'slug' => 'trixie-tennisnyi-myachik',
                'description' => 'Теннисный мячик для собак. Прочная резина с войлоком.',
                'brand_id' => null,
                'category_id' => 11,
                'is_active' => 1,
                'meta_title' => 'Trixie теннисный мячик собака',
                'meta_description' => 'Теннисный мячик Trixie для апортировки собак',
                'meta_keywords' => 'trixie теннисный,мячик собака апортировка',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 47,
                'name' => 'Ferplast фрисби Flyer',
                'slug' => 'ferplast-frisbi-flyer',
                'description' => 'Пластиковый фрисби для активных игр на улице. Легкий и прочный.',
                'brand_id' => null,
                'category_id' => 11,
                'is_active' => 1,
                'meta_title' => 'Ferplast Flyer фрисби собака',
                'meta_description' => 'Фрисби Ferplast Flyer для собак активные игры',
                'meta_keywords' => 'ferplast фрисби,фрисби собака уличные игры',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 48,
                'name' => 'K9 Granit мячик',
                'slug' => 'k9-granit-myachik',
                'description' => 'Прочный резиновый мячик для сильных челюстей. Выдерживает давление.',
                'brand_id' => null,
                'category_id' => 11,
                'is_active' => 1,
                'meta_title' => 'K9 Granit мячик собака',
                'meta_description' => 'Резиновый мячик K9 Granit для мощных собак',
                'meta_keywords' => 'k9 granit,мячик собака прочный челюсти',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 49,
                'name' => 'Chuckit! Ultra мячик',
                'slug' => 'chuckit-ultra-myachik',
                'description' => 'Яркий мячик для метателя Chuckit. Увеличенная дальность броска.',
                'brand_id' => null,
                'category_id' => 11,
                'is_active' => 1,
                'meta_title' => 'Chuckit Ultra мячик собака метатель',
                'meta_description' => 'Мячик Chuckit Ultra для метателя собак',
                'meta_keywords' => 'chuckit ultra,мячик метатель собака',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 50,
                'name' => 'Rogz Grinz мячик зубастый',
                'slug' => 'rogz-grinz-myachik-zubastyi',
                'description' => 'Резиновый мячик с зубастой мордочкой. Массаж десен.',
                'brand_id' => null,
                'category_id' => 11,
                'is_active' => 1,
                'meta_title' => 'Rogz Grinz зубастый мячик собака',
                'meta_description' => 'Мячик Rogz Grinz массаж десен собак',
                'meta_keywords' => 'rogz grinz,мячик зубастый собака десны',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        DB::table('product_variations')->insert([
            [
                'id' => 88,
                'product_id' => 45,
                'name' => 'Kong Classic красный, S',
                'sku' => 'KONG-CLASSIC-S',
                'price' => 1999.00,
                'old_price' => null,
                'stock' => 35,
                'is_default' => 1,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 89,
                'product_id' => 45,
                'name' => 'Kong Classic красный, M',
                'sku' => 'KONG-CLASSIC-M',
                'price' => 2499.00,
                'old_price' => null,
                'stock' => 25,
                'is_default' => 0,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 90,
                'product_id' => 46,
                'name' => 'Trixie теннисный мячик, стандарт',
                'sku' => 'TRIXIE-TENNIS-STD',
                'price' => 399.00,
                'old_price' => null,
                'stock' => 100,
                'is_default' => 1,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 91,
                'product_id' => 46,
                'name' => 'Trixie теннисный мячик, большой',
                'sku' => 'TRIXIE-TENNIS-L',
                'price' => 599.00,
                'old_price' => null,
                'stock' => 70,
                'is_default' => 0,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 92,
                'product_id' => 47,
                'name' => 'Ferplast фрисби Flyer, средний',
                'sku' => 'FERPLAST-FLYER-M',
                'price' => 799.00,
                'old_price' => null,
                'stock' => 60,
                'is_default' => 1,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 93,
                'product_id' => 47,
                'name' => 'Ferplast фрисби Flyer, большой',
                'sku' => 'FERPLAST-FLYER-L',
                'price' => 999.00,
                'old_price' => null,
                'stock' => 40,
                'is_default' => 0,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 94,
                'product_id' => 48,
                'name' => 'K9 Granit мячик, M',
                'sku' => 'K9-GRANIT-M',
                'price' => 1499.00,
                'old_price' => null,
                'stock' => 30,
                'is_default' => 1,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 95,
                'product_id' => 48,
                'name' => 'K9 Granit мячик, L',
                'sku' => 'K9-GRANIT-L',
                'price' => 1999.00,
                'old_price' => null,
                'stock' => 20,
                'is_default' => 0,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 96,
                'product_id' => 49,
                'name' => 'Chuckit! Ultra мячик, средний',
                'sku' => 'CHUCKIT-ULTRA-M',
                'price' => 1299.00,
                'old_price' => null,
                'stock' => 50,
                'is_default' => 1,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 97,
                'product_id' => 49,
                'name' => 'Chuckit! Ultra мячик, большой',
                'sku' => 'CHUCKIT-ULTRA-L',
                'price' => 1699.00,
                'old_price' => null,
                'stock' => 35,
                'is_default' => 0,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 98,
                'product_id' => 50,
                'name' => 'Rogz Grinz мячик зубастый, M',
                'sku' => 'ROGZ-GRINZ-M',
                'price' => 1199.00,
                'old_price' => null,
                'stock' => 45,
                'is_default' => 1,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 99,
                'product_id' => 50,
                'name' => 'Rogz Grinz мячик зубастый, L',
                'sku' => 'ROGZ-GRINZ-L',
                'price' => 1499.00,
                'old_price' => null,
                'stock' => 25,
                'is_default' => 0,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        // ======================================================
        // 6. СОБАКИ -> ЛЕЖАНКИ И ДОМИКИ -> ЛЕЖАНКИ (category_id=14)
        // ======================================================
        DB::table('products')->insert([
            [
                'id' => 51,
                'name' => 'Trixie Ортопедическая лежанка',
                'slug' => 'trixie-ortopedicheskaya-lezhanka',
                'description' => 'Лежанка с ортопедической пеной memory foam. Для собак с проблемами суставов.',
                'brand_id' => null,
                'category_id' => 14,
                'is_active' => 1,
                'meta_title' => 'Trixie ортопедическая лежанка собака',
                'meta_description' => 'Ортопедическая лежанка Trixie memory foam для собак суставы',
                'meta_keywords' => 'trixie ортопедическая,лежанка memory foam,собаки суставы',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 52,
                'name' => 'Good Boy плед лежанка',
                'slug' => 'good-boy-pled-lezhanka',
                'description' => 'Мягкая лежанка-плед из флиса. Съемный чехол машинная стирка.',
                'brand_id' => null,
                'category_id' => 14,
                'is_active' => 1,
                'meta_title' => 'Good Boy плед лежанка собака',
                'meta_description' => 'Лежанка-плед Good Boy флис съемный чехол',
                'meta_keywords' => 'good boy плед,лежанка флис собака',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 53,
                'name' => 'Ferplast лежанка Carlotta',
                'slug' => 'ferplast-lezhanka-carlotta',
                'description' => 'Круглая лежанка с бортиками. Машинная стирка 30°C.',
                'brand_id' => null,
                'category_id' => 14,
                'is_active' => 1,
                'meta_title' => 'Ferplast Carlotta лежанка собака',
                'meta_description' => 'Круглая лежанка Ferplast Carlotta с бортиками',
                'meta_keywords' => 'ferplast carlotta,лежанка круглая бортики',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 54,
                'name' => 'Hunter лежанка Bavaria',
                'slug' => 'hunter-lezhanka-bavaria',
                'description' => 'Немецкое качество. Прочная ткань водоотталкивающая подкладка.',
                'brand_id' => null,
                'category_id' => 14,
                'is_active' => 1,
                'meta_title' => 'Hunter Bavaria лежанка собака',
                'meta_description' => 'Лежанка Hunter Bavaria немецкое качество водоотталкивающая',
                'meta_keywords' => 'hunter bavaria,лежанка немецкая качество',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 55,
                'name' => 'PetFusion ортопедическая',
                'slug' => 'petfusion-ortopedicheskaya',
                'description' => 'Лежанка с ортопедической пеной. Экологичные материалы гипоаллергенная.',
                'brand_id' => null,
                'category_id' => 14,
                'is_active' => 1,
                'meta_title' => 'PetFusion ортопедическая лежанка собака',
                'meta_description' => 'Ортопедическая лежанка PetFusion экологичные гипоаллергенная',
                'meta_keywords' => 'petfusion ортопедическая,лежанка экологичная',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 56,
                'name' => 'Laifugy лежанка домик',
                'slug' => 'laifugy-lezhanka-domik',
                'description' => 'Лежанка-домик с крышей. Для маленьких собак и щенков.',
                'brand_id' => null,
                'category_id' => 14,
                'is_active' => 1,
                'meta_title' => 'Laifugy лежанка домик собака',
                'meta_description' => 'Лежанка-домик Laifugy для маленьких собак щенков',
                'meta_keywords' => 'laifugy домик,лежанка маленькие собаки',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        DB::table('product_variations')->insert([
            [
                'id' => 100,
                'product_id' => 51,
                'name' => 'Trixie Ортопедическая лежанка, S (50x40 см)',
                'sku' => 'TRIXIE-ORTHO-S',
                'price' => 7999.00,
                'old_price' => null,
                'stock' => 15,
                'is_default' => 1,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 101,
                'product_id' => 51,
                'name' => 'Trixie Ортопедическая лежанка, M (70x50 см)',
                'sku' => 'TRIXIE-ORTHO-M',
                'price' => 10999.00,
                'old_price' => null,
                'stock' => 10,
                'is_default' => 0,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 102,
                'product_id' => 52,
                'name' => 'Good Boy плед лежанка, S (60x45 см)',
                'sku' => 'GOODBOY-PLED-S',
                'price' => 2999.00,
                'old_price' => null,
                'stock' => 40,
                'is_default' => 1,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 103,
                'product_id' => 52,
                'name' => 'Good Boy плед лежанка, L (90x65 см)',
                'sku' => 'GOODBOY-PLED-L',
                'price' => 5999.00,
                'old_price' => null,
                'stock' => 25,
                'is_default' => 0,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 104,
                'product_id' => 53,
                'name' => 'Ferplast лежанка Carlotta, S (50 см диаметр)',
                'sku' => 'FERPLAST-CARL-S',
                'price' => 3499.00,
                'old_price' => null,
                'stock' => 35,
                'is_default' => 1,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 105,
                'product_id' => 53,
                'name' => 'Ferplast лежанка Carlotta, M (70 см диаметр)',
                'sku' => 'FERPLAST-CARL-M',
                'price' => 5999.00,
                'old_price' => null,
                'stock' => 20,
                'is_default' => 0,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 106,
                'product_id' => 54,
                'name' => 'Hunter лежанка Bavaria, M (75x55 см)',
                'sku' => 'HUNTER-BAV-M',
                'price' => 6999.00,
                'old_price' => null,
                'stock' => 20,
                'is_default' => 1,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 107,
                'product_id' => 54,
                'name' => 'Hunter лежанка Bavaria, L (95x70 см)',
                'sku' => 'HUNTER-BAV-L',
                'price' => 9999.00,
                'old_price' => null,
                'stock' => 12,
                'is_default' => 0,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 108,
                'product_id' => 55,
                'name' => 'PetFusion ортопедическая, M (71x53 см)',
                'sku' => 'PETFUSION-M',
                'price' => 8999.00,
                'old_price' => null,
                'stock' => 18,
                'is_default' => 1,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 109,
                'product_id' => 55,
                'name' => 'PetFusion ортопедическая, L (91x66 см)',
                'sku' => 'PETFUSION-L',
                'price' => 12999.00,
                'old_price' => null,
                'stock' => 8,
                'is_default' => 0,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 110,
                'product_id' => 56,
                'name' => 'Laifugy лежанка домик, S (60x45x30 см)',
                'sku' => 'LAIFUGY-S',
                'price' => 4499.00,
                'old_price' => null,
                'stock' => 30,
                'is_default' => 1,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 111,
                'product_id' => 56,
                'name' => 'Laifugy лежанка домик, M (80x60x35 см)',
                'sku' => 'LAIFUGY-M',
                'price' => 6999.00,
                'old_price' => null,
                'stock' => 20,
                'is_default' => 0,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        // ======================================================
        // АТРИБУТЫ ДЛЯ ПРОДУКТОВ (product_attributes)
        // ======================================================
        DB::table('product_attributes')->insert([
            // Для Grandin Hypoallergenic (id=21)
            ['id' => 35, 'product_id' => 21, 'key' => 'Размер питомца', 'value' => 'Все размеры', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 36, 'product_id' => 21, 'key' => 'Тип корма', 'value' => 'Сухой', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 37, 'product_id' => 21, 'key' => 'Класс корма', 'value' => 'Суперпремиум', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 38, 'product_id' => 21, 'key' => 'Особенности', 'value' => 'Беззерновой, гипоаллергенный', 'created_at' => $now, 'updated_at' => $now],

            // Для Klicker Adult (id=22)
            ['id' => 39, 'product_id' => 22, 'key' => 'Размер питомца', 'value' => 'Мелкие породы', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 40, 'product_id' => 22, 'key' => 'Тип корма', 'value' => 'Сухой', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 41, 'product_id' => 22, 'key' => 'Класс корма', 'value' => 'Премиум', 'created_at' => $now, 'updated_at' => $now],

            // Для Royal Canin Mini Adult (id=23)
            ['id' => 42, 'product_id' => 23, 'key' => 'Размер питомца', 'value' => 'Мелкие породы', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 43, 'product_id' => 23, 'key' => 'Возраст', 'value' => 'Взрослые (1-7 лет)', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 44, 'product_id' => 23, 'key' => 'Тип корма', 'value' => 'Сухой', 'created_at' => $now, 'updated_at' => $now],

            // Для ABBA Premium (id=24)
            ['id' => 45, 'product_id' => 24, 'key' => 'Размер питомца', 'value' => 'Все размеры', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 46, 'product_id' => 24, 'key' => 'Тип корма', 'value' => 'Сухой', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 47, 'product_id' => 24, 'key' => 'Класс корма', 'value' => 'Суперпремиум', 'created_at' => $now, 'updated_at' => $now],

            // Для RURRI Classic (id=25)
            ['id' => 48, 'product_id' => 25, 'key' => 'Размер питомца', 'value' => 'Все размеры', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 49, 'product_id' => 25, 'key' => 'Тип корма', 'value' => 'Сухой', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 50, 'product_id' => 25, 'key' => 'Класс корма', 'value' => 'Эконом', 'created_at' => $now, 'updated_at' => $now],

            // Для Ownat Grain Free (id=26)
            ['id' => 51, 'product_id' => 26, 'key' => 'Размер питомца', 'value' => 'Все размеры', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 52, 'product_id' => 26, 'key' => 'Тип корма', 'value' => 'Сухой', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 53, 'product_id' => 26, 'key' => 'Класс корма', 'value' => 'Холистик', 'created_at' => $now, 'updated_at' => $now],

            // Для кошачьих кормов (id=27-32)
            ['id' => 54, 'product_id' => 27, 'key' => 'Тип корма', 'value' => 'Сухой', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 55, 'product_id' => 27, 'key' => 'Особенности', 'value' => 'Для чувствительного пищеварения', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 56, 'product_id' => 28, 'key' => 'Тип корма', 'value' => 'Сухой', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 57, 'product_id' => 28, 'key' => 'Особенности', 'value' => 'Для домашних кошек, контроль веса', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 58, 'product_id' => 29, 'key' => 'Тип корма', 'value' => 'Сухой', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 59, 'product_id' => 29, 'key' => 'Особенности', 'value' => 'Для стерилизованных кошек', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 60, 'product_id' => 30, 'key' => 'Тип корма', 'value' => 'Сухой', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 61, 'product_id' => 30, 'key' => 'Особенности', 'value' => 'Гипоаллергенный', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 62, 'product_id' => 31, 'key' => 'Тип корма', 'value' => 'Сухой', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 63, 'product_id' => 31, 'key' => 'Вкус', 'value' => 'Курица', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 64, 'product_id' => 32, 'key' => 'Тип корма', 'value' => 'Сухой', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 65, 'product_id' => 32, 'key' => 'Особенности', 'value' => 'Для домашних кошек', 'created_at' => $now, 'updated_at' => $now],

            // Для ошейников (id=33-38)
            ['id' => 66, 'product_id' => 33, 'key' => 'Материал', 'value' => 'Нейлон', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 67, 'product_id' => 33, 'key' => 'Особенности', 'value' => 'С ручкой для контроля', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 68, 'product_id' => 34, 'key' => 'Материал', 'value' => 'Натуральная кожа', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 69, 'product_id' => 35, 'key' => 'Материал', 'value' => 'Парашютная ткань', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 70, 'product_id' => 36, 'key' => 'Материал', 'value' => 'Усиленный нейлон', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 71, 'product_id' => 37, 'key' => 'Материал', 'value' => 'Натуральная кожа (плетеный)', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 72, 'product_id' => 38, 'key' => 'Материал', 'value' => 'Альпинистский нейлон', 'created_at' => $now, 'updated_at' => $now],

            // Для наполнителей (id=39-44)
            ['id' => 73, 'product_id' => 39, 'key' => 'Тип наполнителя', 'value' => 'Древесный, комкующийся', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 74, 'product_id' => 40, 'key' => 'Тип наполнителя', 'value' => 'Древесный, целлюлозный', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 75, 'product_id' => 41, 'key' => 'Тип наполнителя', 'value' => 'Древесный (хвойные породы)', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 76, 'product_id' => 42, 'key' => 'Тип наполнителя', 'value' => 'Древесный, комкующийся', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 77, 'product_id' => 43, 'key' => 'Тип наполнителя', 'value' => 'Древесный премиум', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 78, 'product_id' => 44, 'key' => 'Тип наполнителя', 'value' => 'Древесный с травами', 'created_at' => $now, 'updated_at' => $now],

            // Для игрушек (id=45-50)
            ['id' => 79, 'product_id' => 45, 'key' => 'Материал', 'value' => 'Натуральная резина', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 80, 'product_id' => 45, 'key' => 'Тип игрушки', 'value' => 'Для жевания, апортировки', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 81, 'product_id' => 46, 'key' => 'Материал', 'value' => 'Резина с войлоком', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 82, 'product_id' => 47, 'key' => 'Материал', 'value' => 'Пластик', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 83, 'product_id' => 47, 'key' => 'Тип игрушки', 'value' => 'Фрисби', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 84, 'product_id' => 48, 'key' => 'Материал', 'value' => 'Прочная резина', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 85, 'product_id' => 49, 'key' => 'Материал', 'value' => 'Резина', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 86, 'product_id' => 49, 'key' => 'Особенности', 'value' => 'Для метателя Chuckit', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 87, 'product_id' => 50, 'key' => 'Материал', 'value' => 'Резина', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 88, 'product_id' => 50, 'key' => 'Особенности', 'value' => 'Массаж десен', 'created_at' => $now, 'updated_at' => $now],

            // Для лежанок (id=51-56)
            ['id' => 89, 'product_id' => 51, 'key' => 'Материал', 'value' => 'Memory foam', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 90, 'product_id' => 51, 'key' => 'Особенности', 'value' => 'Ортопедическая', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 91, 'product_id' => 52, 'key' => 'Материал', 'value' => 'Флис', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 92, 'product_id' => 52, 'key' => 'Особенности', 'value' => 'Съемный чехол', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 93, 'product_id' => 53, 'key' => 'Форма', 'value' => 'Круглая с бортиками', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 94, 'product_id' => 54, 'key' => 'Особенности', 'value' => 'Водоотталкивающая', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 95, 'product_id' => 55, 'key' => 'Материал', 'value' => 'Ортопедическая пена', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 96, 'product_id' => 55, 'key' => 'Особенности', 'value' => 'Гипоаллергенная', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 97, 'product_id' => 56, 'key' => 'Тип', 'value' => 'Лежанка-домик', 'created_at' => $now, 'updated_at' => $now],
        ]);

        // ======================================================
        // АТРИБУТЫ ДЛЯ ВАРИАЦИЙ (variation_attributes)
        // ======================================================
        DB::table('variation_attributes')->insert([
            // Вариации кормов собак
            ['id' => 15, 'variation_id' => 41, 'key' => 'вес', 'value' => '2.7 кг', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 16, 'variation_id' => 41, 'key' => 'вкус', 'value' => 'ягненок', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 17, 'variation_id' => 42, 'key' => 'вес', 'value' => '11.2 кг', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 18, 'variation_id' => 42, 'key' => 'вкус', 'value' => 'ягненок', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 19, 'variation_id' => 43, 'key' => 'вес', 'value' => '0.5 кг', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 20, 'variation_id' => 44, 'key' => 'вес', 'value' => '2 кг', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 21, 'variation_id' => 45, 'key' => 'вес', 'value' => '2 кг', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 22, 'variation_id' => 46, 'key' => 'вес', 'value' => '4 кг', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 23, 'variation_id' => 47, 'key' => 'вес', 'value' => '3 кг', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 24, 'variation_id' => 48, 'key' => 'вес', 'value' => '12 кг', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 25, 'variation_id' => 49, 'key' => 'вес', 'value' => '3 кг', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 26, 'variation_id' => 50, 'key' => 'вес', 'value' => '15 кг', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 27, 'variation_id' => 51, 'key' => 'вес', 'value' => '2 кг', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 28, 'variation_id' => 52, 'key' => 'вес', 'value' => '12 кг', 'created_at' => $now, 'updated_at' => $now],

            // Вариации кормов кошек
            ['id' => 29, 'variation_id' => 53, 'key' => 'вес', 'value' => '1 кг', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 30, 'variation_id' => 54, 'key' => 'вес', 'value' => '4 кг', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 31, 'variation_id' => 55, 'key' => 'вес', 'value' => '1.5 кг', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 32, 'variation_id' => 56, 'key' => 'вес', 'value' => '4 кг', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 33, 'variation_id' => 57, 'key' => 'вес', 'value' => '2 кг', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 34, 'variation_id' => 58, 'key' => 'вес', 'value' => '4 кг', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 35, 'variation_id' => 59, 'key' => 'вес', 'value' => '2 кг', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 36, 'variation_id' => 60, 'key' => 'вес', 'value' => '10 кг', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 37, 'variation_id' => 61, 'key' => 'вес', 'value' => '1.5 кг', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 38, 'variation_id' => 62, 'key' => 'вес', 'value' => '7 кг', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 39, 'variation_id' => 63, 'key' => 'вес', 'value' => '2 кг', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 40, 'variation_id' => 64, 'key' => 'вес', 'value' => '10 кг', 'created_at' => $now, 'updated_at' => $now],

            // Вариации ошейников
            ['id' => 41, 'variation_id' => 65, 'key' => 'размер', 'value' => 'L (42-65 см)', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 42, 'variation_id' => 65, 'key' => 'цвет', 'value' => 'черный', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 43, 'variation_id' => 66, 'key' => 'размер', 'value' => 'M (38-48 см)', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 44, 'variation_id' => 66, 'key' => 'цвет', 'value' => 'черный', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 45, 'variation_id' => 67, 'key' => 'размер', 'value' => 'M (30-45 см)', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 46, 'variation_id' => 68, 'key' => 'размер', 'value' => 'L (40-60 см)', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 47, 'variation_id' => 69, 'key' => 'размер', 'value' => 'S (25-40 см)', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 48, 'variation_id' => 70, 'key' => 'размер', 'value' => 'M (35-55 см)', 'created_at' => $now, 'updated_at' => $now],

            // Вариации наполнителей
            ['id' => 49, 'variation_id' => 76, 'key' => 'объем', 'value' => '10 л', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 50, 'variation_id' => 77, 'key' => 'объем', 'value' => '20 л', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 51, 'variation_id' => 78, 'key' => 'вес', 'value' => '6 кг', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 52, 'variation_id' => 79, 'key' => 'вес', 'value' => '17 кг', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 53, 'variation_id' => 80, 'key' => 'объем', 'value' => '5 л', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 54, 'variation_id' => 81, 'key' => 'объем', 'value' => '10 л', 'created_at' => $now, 'updated_at' => $now],

            // Вариации игрушек
            ['id' => 55, 'variation_id' => 88, 'key' => 'размер', 'value' => 'S', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 56, 'variation_id' => 89, 'key' => 'размер', 'value' => 'M', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 57, 'variation_id' => 90, 'key' => 'размер', 'value' => 'стандарт', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 58, 'variation_id' => 91, 'key' => 'размер', 'value' => 'большой', 'created_at' => $now, 'updated_at' => $now],

            // Вариации лежанок
            ['id' => 59, 'variation_id' => 100, 'key' => 'размер', 'value' => 'S (50x40 см)', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 60, 'variation_id' => 101, 'key' => 'размер', 'value' => 'M (70x50 см)', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 61, 'variation_id' => 102, 'key' => 'размер', 'value' => 'S (60x45 см)', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 62, 'variation_id' => 103, 'key' => 'размер', 'value' => 'L (90x65 см)', 'created_at' => $now, 'updated_at' => $now],
        ]);
    }
}
